### ISSUE TITLE
collector errors in dev stack

### ISSUE THREAD

**Issue by Dieterbe** [raintank/raintank-docker#5]
after setup_dev.sh and launch.dev i get this:

```
<upervisorctl restart all; tail -10f /var/log/raintank/collector.log
collector: ERROR (abnormal termination)
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/raintank/raintank-collector/checks/dns.js:2:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

module.js:340
    throw err;
          ^
Error: Cannot find module 'native-dns'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/raintank/raintank-collector/checks/dns.js:2:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

module.js:340
    throw err;
          ^
Error: Cannot find module 'native-dns'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/raintank/raintank-collector/checks/dns.js:2:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by Dieterbe** [comment]
this was caused due to one of my commits in #4 , i added the bugfix in there as well.
